name: Update Release Versions

on:
  workflow_call:
    inputs:
      version:
        description: "The version that was just released (semver compliant)"
        required: true
        type: string
      release_ref:
        description: "The ref the release versions should point to"
        required: true
        type: string
    outputs:
      major:
        description: "The major version"
        value: ${{ jobs.update_release_versions.outputs.major }}
      minor:
        description: "The minor version"
        value: ${{ jobs.update_release_versions.outputs.minor }}
      patch:
        description: "The patch version"
        value: ${{ jobs.update_release_versions.outputs.patch }}
      major_tag:
        description: "The major tag that was created (the version number, e.g. 1)"
        value: ${{ jobs.update_release_versions.outputs.major_tag }}
      minor_tag:
        description: "The minor tag that was created (the version number, e.g. 1.2)"
        value: ${{ jobs.update_release_versions.outputs.minor_tag }}
jobs:
  update_release_versions:
    name: Update Release Versions
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.parse.outputs.major }}
      minor: ${{ steps.parse.outputs.minor }}
      patch: ${{ steps.parse.outputs.patch }}
      major_tag: ${{ steps.update.outputs.major }}
      minor_tag: ${{ steps.update.outputs.minor }}
    steps:
      - name: Parse version
        id: parse
        run: |
          echo "major=$(echo ${{ inputs.version }} | cut -d '.' -f 1)" >> $GITHUB_OUTPUT
          echo "minor=$(echo ${{ inputs.version }} | cut -d '.' -f 2)" >> $GITHUB_OUTPUT
          echo "patch=$(echo ${{ inputs.version }} | cut -d '.' -f 3)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update tags
        id: update
        run: |
          MAJOR="${{ steps.parse.outputs.major }}"
          MINOR="${{ steps.parse.outputs.major }}.${{ steps.parse.outputs.minor }}"
          TARGET="${{ inputs.release_ref }}"
          git tag -f $MAJOR $TARGET
          git tag -f $MINOR $TARGET
          git push origin $MAJOR $MINOR --force
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT